# Copy this file to keystore.properties and fill in your actual values
# This file should NEVER be committed to version control

storeFile=/Users/matthewshoemaker/.android/release.keystore
storePassword=listery123
keyAlias=listery-release
keyPassword=listery123
